@startuml
!include incl/skin.puml

title Content Renderer

namespace Joomla.Content {
    interface Content
}

namespace Joomla.Frontend {
    interface Renderer
}

Joomla.Content.Content <-> Joomla.Frontend.Renderer: "«uses»"

namespace Joomla.Frontend.Http {
    interface Renderer .r.|> Joomla.Frontend.Renderer

    class HtmlRenderer implements Renderer {
        -ScriptStrategy <b>clientScript</b>
        +<b>setScriptStrategy</b>(ScriptStrategy)
    }

    class PdfRenderer implements Renderer
    class DocBookRenderer implements Renderer
}

namespace Joomla.Frontend.Rest {
    interface Renderer .l.|> Joomla.Frontend.Renderer

    class XmlRenderer implements Renderer
    class JsonRenderer implements Renderer
}

namespace Joomla.Frontend.Cli {
    class Renderer .u.|> Joomla.Frontend.Renderer
    class AnsiRenderer extends Renderer
}

namespace Joomla.Frontend {
    class DynamicRendererImplementation << (T,white) >> {
        -Callable[] <b>handlers</b>
        +<b>registerContentType</b>(string, Callable)
        +<b>__call</b>(string [, ...])
    }
}

Joomla.Frontend.Renderer *-> Joomla.Frontend.DynamicRendererImplementation

@enduml
