@startuml
!include incl/skin.puml

title Content Structure

namespace Joomla.Content {
    interface Content {
        +{abstract} <b>accept</b>(Renderer)
    }
    interface ContentItem extends Content
    interface ContentGroup extends Content
    ContentGroup *-> "n" Content: children

    class Category implements ContentGroup
    class Page implements ContentGroup

    class Paragraph implements ContentItem
    class Image implements ContentItem
}

namespace Joomla.Frontend {
    interface Renderer {
    }
}

Joomla.Content.Content <-> Joomla.Frontend.Renderer: "«uses»"
@enduml
