@startuml
!include incl/skin.puml

title Frontends
namespace Joomla.Frontend.Http {
    class Request implements Joomla.Frontend.Input
    class Response implements Joomla.Frontend.Output
    note "index.php" as FrontControllerHttp #white
}
namespace Joomla.Frontend.Rest {
    class Request implements Joomla.Frontend.Input
    class Response implements Joomla.Frontend.Output
    note "api.php" as FrontControllerRest #white
}
namespace Joomla.Frontend.Cli {
    class Input implements Joomla.Frontend.Input
    class Output implements Joomla.Frontend.Output
    note "joomla.php" as FrontControllerCli #white
}
@enduml
