@startuml
!include incl/skin.puml
hide << Entity >> circle
hide << Association >> circle

title Routing\n

interface RouterStrategy {
    resolve(ServerRequestInterface request, RouterStrategy next = null): ServerRequestInterface
}

class Router {
    route(ServerRequestInterface request): Command
}
class CliRoutingStrategy
class ApiRoutingStrategy
class LegacyRoutingStrategy << deprecated >>
class DefaultRoutingStrategy

Router o--> RouterStrategy : strategies
class CliRoutingStrategy implements RouterStrategy
class ApiRoutingStrategy implements RouterStrategy
class LegacyRoutingStrategy implements RouterStrategy
class DefaultRoutingStrategy implements RouterStrategy

interface UrlBuilder {
    build(Array vars): string
}

package SeoComponent {
    class SeoUrl << Entity >> {
        PK string url
        string entity_name
        FK entity_id
        string view
    }
    class SeoRoutingStrategy implements RouterStrategy, UrlBuilder {
    }
}
@enduml
